config/routes.rb
Rails.application.routes.draw do

  get 'carts/show'

  root 'products#index'

  get 'cart' => 'carts#show', as: 'cart'
  delete 'cart' => 'carts#destroy'
  get 'checkout' => 'orders#create_fast'
  get 'products' => redirect('/')

  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'

  resources :orders
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
  belongs_to :product

  validate :belongs_present?

  def total_price
    quantity * product.price
  end

  private

  def belongs_present?
    errors.add(:belongs, 'Order or Cart was not present!') unless
      order.present? || cart.present?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def product_quantity(product_id)
    line_items.find_by(product_id: product_id).quantity
  rescue
    0
  end

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  private

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart

    if current_cart.products.include?(chosen_product)
      @line_item = current_cart.line_items.find_by(product_id: chosen_product)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = current_cart
      @line_item.product = chosen_product
    end

    @line_item.save
    # redirect_to cart_path
    redirect_to root_path
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path
  end

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    end
    @line_item.save
    redirect_to cart_path
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id, :cart_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    session[:chart]
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to root_path, notice: "Order ##{@order.id} was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_fast
    @order = Order.new
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path, notice: "Заказ №#{@order.id} успешно добавлен."
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: 'Продукт успешно добавлен.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to root_path, notice: 'Продукт успешно обновлен.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Продукт успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_roubles(number)
    number_to_currency(number,
                       unit: '₽',
                       precision: 2,
                       format: '%n %u',
                       separator: ',',
                       delimiter: ' ')
  end
end

app/views/carts/show.html.haml
%h2 Корзина
%ul
  - @cart.line_items.order(:id).each do |line_item|
    %li
      %b Продукт:
      = line_item.product.name
      %b Цена:
      = number_to_roubles(line_item.product.price)
      %b Количество:
      =line_item.quantity
      %b Общая цена:
      =number_to_roubles(line_item.total_price)
    %ul
      %li
        = link_to 'Добавить один', line_item_add_path(:id => line_item), method: :post
        = link_to 'Удалить один', line_item_reduce_path(:id => line_item), method: :post
      %li
        = link_to 'Удалить позицию', line_item_path(line_item), method: :delete

%h3
  Итого:
  = number_to_roubles(@cart.sub_total)

-#= link_to 'Proceed to checkout', new_order_path
= link_to 'Оформить заказ', checkout_path
-#= link_to 'Checkout', :controller => :orders_controller, :action => :create

= link_to 'Очистить корзину', cart_path, method: :delete, data: {confirm: 'Вы уверены?'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for?(:title) ? yield(:title) : 'ShopExample'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href=root_path) ShopExample
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.navbar-nav.mr-auto
            -#%li= link_to "Link 1", "/path1"
          %a.navbar-text.pull-right(href=cart_path)
            Корзина (
            -sum = 0
            - @current_cart.line_items.each{|i| sum += i.quantity }
            = sum
            )

    .container
      .row
        .col-lg-9
          = yield
        .col-lg-3
          -#.well.sidebar-nav
          -#  %h3 Sidebar
          -#  %ul.nav.nav-list
          -#    %li.nav-header Sidebar
          -#    %li= link_to "Link 1", "/path1"
          -#    %li= link_to "Link 2", "/path2"
          -#    %li= link_to "Link 3", "/path3"
      -#%footer
      -#  %p &copy; Company 2017

app/views/orders/_form.html.haml
= form_with(model: order, local: true) do |form|
  - if order.errors.any?
    #error_explanation
      %h2
        = pluralize(order.errors.count, "error")
        prohibited this order from being saved:
      %ul
        - order.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/orders/edit.html.haml
%h1 Изменение заказа
= render 'form', order: @order
= link_to 'Show', @order
|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%p#notice= notice
%h1 Заказы
%table
  %thead
    %tr
      %th №
      %th Товары
      %th Общая цена
      %th{:colspan => "1"}
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.id
        - products = order.products
        - product_quantity = products.map{|p| [p.id, order.product_quantity(p.id)]}.to_h
        %td= products.map {|p| p.name + " x#{product_quantity[p.id]}" }.join(', ')
        %td= number_to_roubles(order.sub_total)
        -#%td= link_to 'Show', order
        -#%td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Удалить', order, method: :delete, data: { confirm: 'Вы уверены?' }
%br/
-#= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
%h1 Новый заказ
= render 'form', order: @order
= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice
= link_to 'Изменить', edit_order_path(@order)
|
= link_to 'Назад', orders_path

app/views/products/_form.html.haml
= form_with(model: product, local: true) do |form|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label 'Название'
    = form.text_field :name, id: :product_name, required: true, autofocus: true, placeholder: 'Введите название продукта'
  .field
    = form.label 'Цена'
    = form.number_field :price, id: :product_price
  .actions
    = form.submit 'Готово'

app/views/products/edit.html.haml
%h1 Изменение продукта
= render 'form', product: @product
-#= link_to 'Показать', @product
-#|
= link_to 'Назад', products_path

app/views/products/index.html.haml
%p#notice= notice
%h1 Продукты
%table
  %thead
    %tr
      %th Название
      %th Цена
      %th{:colspan => "3"}
  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= number_to_roubles(product.price)
        -#%td= link_to 'Показать', product
        %td= link_to 'Править', edit_product_path(product)
        %td= link_to 'Удалить', product, method: :delete, data: { confirm: 'Вы уверены?' }
        %td= button_to "Добавить #{product.name} в корзину", line_items_path(:product_id => product.id)
%br/
= link_to 'Новый продукт', new_product_path

app/views/products/new.html.haml
%h1 Новый продукт
= render 'form', product: @product
= link_to 'Назад', products_path

app/views/products/show.html.haml
%p#notice= notice
%p
  %strong Название:
  = @product.name
%p
  %strong Цена:
  = @product.price
= link_to 'Edit', edit_product_path(@product)
|
= link_to 'Back', products_path